theme: jekyll-theme-midnight
version:     "0000--08-Feb-2022"
copyright:   "2022"
author:      "kolokopo"
title:       "Bookmarks page"
githublink:  "https://github.com/kolokopo/bookmarks/"
myloglink:   "TXT/log.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
